version: "2.1"

services:
  mq:
    image: "webcenter/activemq"
  # volumes:
  #     - ./conf/activemq.xml:/opt/activemq/conf/activemq.xml
    ports:
      - 1883:1883
      - 5672:5672
      - 8161:8161
      - 61613:61613
      - 61614:61614
      - 61616:61616

